apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  labels:
    app: nodejs-app
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30036   # Optional: choose a specific port in NodePort range
